language: rust
rust: nightly

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y valgrind
    - wget "https://github.com/jedisct1/libsodium/releases/download/1.0.3/libsodium-1.0.3.tar.gz"
    - tar -xzf libsodium-1.0.3.tar.gz
    - cd libsodium-1.0.3 && ./configure --prefix=/usr && make && sudo make install && cd ..

script: cd cryptobox-c && make test
