[package]
name         = "cryptobox-c"
version      = "0.6.0"
authors      = ["Roman S. Borschel <roman@pkaboo.org>", "Toralf Wittner <tw@dtex.org>"]
description  = "C-FFI to cryptobox"
homepage     = "https://github.com/shared-secret/cryptobox-c"
repository   = "git@github.com:shared-secret/cryptobox-c.git"
license      = "MPL-2.0"

[lib]
name         = "cryptobox"
crate-type   = ["dylib"]

[dependencies]
libc = ">= 0.1.12"

[dependencies.proteus]
git = "https://github.com/shared-secret/proteus"
tag = "v0.4.1"

[dependencies.cryptobox]
git = "https://github.com/shared-secret/cryptobox"
tag = "v0.6.0"
